### ISSUE TITLE
多个bug及建议,环境Ubuntu18

### ISSUE THREAD

**Issue by ydsjqt** [SpongeNobody/Clashy#24] opened 2020-02-29 21:07 UTC
1，setting 中设置端口，重新启动后又被还原。没有写到配置文件中
2.没法配置多个ss ，配置一个可以用，多个就 未知错误
3 有事点击show clashy 无法显示程序的主面板，啥反应都没用
4 建议 软件的使用说明文档给的详细些

**Comment by SpongeNobody** [comment] 2020-03-03 06:58
1. Currently Clashy won't save port settings to `Clash`'s configuration file due to it might be updated from the service provider and port settings will be reset. I will fix this by saving port settings to Clashy's configuration file in the next release.

2. What do you mean "can not add multiple ss"? Usually the "Unknown Error" is caused by attempting to use an invalid clash configuration file.

3. Known issue due to I was using Unity desktop environment instead of Gnome. And I've changed to Gnome recently so this issue will be resolved in the next release too.

4. I'm just too busy (~~lazy~~) to write the documents 😂. Can't guarantee when this will be done. 

Thanks for thee feedback 🙏

**Comment by ydsjqt** [comment] 2020-03-03 07:54
thank you

SpongeNobody <notifications@github.com> 于2020年3月3日周二 下午2:58写道：

**Comment by SpongeNobody** [comment] 2020-03-26 05:48
#3 Fixed in 0.1.13

Rest issues will be fixed in the next release.

**Comment by debugAllTheTime** [comment] 2020-04-04 08:04
is this problem fixed？

**Comment by SpongeNobody** [comment] 2020-04-10 02:38
@debugAllTheTime Not yet except the `Clashy main panel not showing`. I've been busy recently.

**Comment by SpongeNobody** [comment] 2020-05-04 09:38
Issue #1 Solved. Documentations are not counted as issues. Closing this for now. Thanks.

**Closed by SpongeNobody** 2020-05-04 09:38 UTC
Labels: bug, enhancement
